src/Entity/Article.php
<?php
namespace App\Entity;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ArticleRepository")
 * @ORM\HasLifecycleCallbacks
 */
class Article
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="text")
     */
    private $texte;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien_youtube;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Album", inversedBy="articles")
     * @ORM\JoinColumn(nullable=true)
     */
    private $album;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Aime", mappedBy="article")
     */
    private $aimes;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="article")
     */
    private $commentaires;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateur;
    /**
     * @ORM\Column(type="boolean")
     */
    private $no_kill;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="article", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Vich\UploadableField(mapping="article_images", fileNameProperty="photo")
     * @var File
     * @Assert\Image(mimeTypes={ "image/jpeg", "image/jpg", "image/png"  }, mimeTypesMessage = "Extension valide : .jpeg .png .jpg", groups = {"create"})
     */
    private $pictureFiles;


    public function __construct()
    {

        $this->aimes = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->pictures = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }
    public function getLibelle(): ?string
    {
        return $this->libelle;
    }
    /**
     * @return mixed
     */
    public function getNoKill()
    {
        return $this->no_kill;
    }
    /**
     * @param mixed $no_kill
     */
    public function setNoKill($no_kill): void
    {
        $this->no_kill = $no_kill;
    }
    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;
        return $this;
    }
    public function getTexte(): ?string
    {
        return $this->texte;
    }
    public function setTexte(string $texte): self
    {
        $this->texte = $texte;
        return $this;
    }

    public function getLienYoutube(): ?string
    {
        return $this->lien_youtube;
    }
    public function setLienYoutube(?string $lien_youtube): self
    {
        $this->lien_youtube = $lien_youtube;
        return $this;
    }
    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }
    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;
        return $this;
    }
    public function getAlbum(): ?Album
    {
        return $this->album;
    }
    public function setAlbum(?Album $album): self
    {
        $this->album = $album;
        return $this;
    }

    /**
     * @return Collection|Aime[]
     */
    public function getAimes(): Collection
    {
        return $this->aimes;
    }
    public function addAime(Aime $aime): self
    {
        if (!$this->aimes->contains($aime)) {
            $this->aimes[] = $aime;
            $aime->setArticle($this);
        }
        return $this;
    }
    public function removeAime(Aime $aime): self
    {
        if ($this->aimes->contains($aime)) {
            $this->aimes->removeElement($aime);
            // set the owning side to null (unless already changed)
            if ($aime->getArticle() === $this) {
                $aime->setArticle(null);
            }
        }
        return $this;
    }
    /**
     * @return Collection|Commentaire[]
     */
    public function getCommentaires(): Collection
    {
        return $this->commentaires;
    }
    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setArticle($this);
            $this->date_creation = new \DateTime('now');
        }
        return $this;
    }
    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getArticle() === $this) {
                $commentaire->setArticle(null);
            }
        }
        return $this;
    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        $this->date_creation = new \DateTime();
    }
    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->date_maj = new \DateTime();
    }
    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }
    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;
        return $this;
    }
    /**
     * @return string
     */
    public function __toString()
    {
        return (string) $this->getLibelle();
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setArticle($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getArticle() === $this) {
                $picture->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }
    /**
     * @param mixed $pictureFiles
     * @return Article
     */
    public function setPictureFiles($pictureFiles): self
    {
        foreach($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setPhotoFile($pictureFile);
            $this->addPicture($picture);
        }
        $this->pictureFiles = $pictureFiles;
        return $this;
    }


}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UtilisateurRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class Utilisateur implements UserInterface, \Serializable
{


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $commune;


    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_web;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_association;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_president;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom_president;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="utilisateur")
     */
    private $evenements;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Produit", mappedBy="Utilisateur")
     */
    private $produits;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Album", mappedBy="utilisateur")
     */
    private $albums;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Aime", mappedBy="utilisateur")
     */
    private $aimes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Suivre", mappedBy="utilisateur_from")
     */
    private $suivis;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Suivre", mappedBy="utilisateur_to")
     */
    private $suiveurs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="utilisateur")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(name="photo", type="string", length=255, nullable=true)
     * @var string
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="utilisateur_images", fileNameProperty="photo")
     * @var File
     * @Assert\Image(mimeTypes={ "image/jpeg", "image/jpg", "image/png"  }, mimeTypesMessage = "Extension valide : .jpeg .png .jpg", groups = {"create"})
     */
    private $photoFile;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="utilisateur", orphanRemoval=true)
     */
    private $articles;





    public function __construct()
    {
        $this->evenements = new ArrayCollection();
        $this->produits = new ArrayCollection();
        $this->albums = new ArrayCollection();
        $this->aimes = new ArrayCollection();
        $this->suivis = new ArrayCollection();
        $this->suiveurs = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(string $commune): self
    {
        $this->commune = $commune;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(string $site_web): self
    {
        $this->site_web = $site_web;

        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(?string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(?string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getNomAssociation(): ?string
    {
        return $this->nom_association;
    }

    public function setNomAssociation(?string $nom_association): self
    {
        $this->nom_association = $nom_association;

        return $this;
    }

    public function getNomPresident(): ?string
    {
        return $this->nom_president;
    }

    public function setNomPresident(?string $nom_president): self
    {
        $this->nom_president = $nom_president;

        return $this;
    }

    public function getPrenomPresident(): ?string
    {
        return $this->prenom_president;
    }

    public function setPrenomPresident(?string $prenom_president): self
    {
        $this->prenom_president = $prenom_president;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setUtilisateur($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->contains($evenement)) {
            $this->evenements->removeElement($evenement);
            // set the owning side to null (unless already changed)
            if ($evenement->getUtilisateur() === $this) {
                $evenement->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setUtilisateur($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->contains($produit)) {
            $this->produits->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getUtilisateur() === $this) {
                $produit->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Album[]
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->albums->contains($album)) {
            $this->albums[] = $album;
            $album->setUtilisateur($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->albums->contains($album)) {
            $this->albums->removeElement($album);
            // set the owning side to null (unless already changed)
            if ($album->getUtilisateur() === $this) {
                $album->setUtilisateur(null);
            }
        }

        return $this;
    }

   

    

    /**
     * @return Collection|Aime[]
     */
    public function getAimes(): Collection
    {
        return $this->aimes;
    }

    public function addAime(Aime $aime): self
    {
        if (!$this->aimes->contains($aime)) {

templates/default/homepage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}



        <div class="container-titre-article">
            <h1 class="mes-articles"><i class="fas fa-home"></i> Accueil</h1>
        </div>
        <div class="separation-article-accueil"></div>
    <div class="container-home">
        <div class="main-article">
            {% for article in articles %}
            <div class="container__article">
                <div class="container__article-titre">
                    <h3>{{ article.album }}</h3>
                    <p class="date-article">{{ article.dateCreation ? article.dateCreation|date('d-m-Y') : '' }}</p>
                </div>
                <div class="container__contenu">


                    {% for picture in article.pictures | slice (0,1)%}


                        <img class="card-img-top" src="{{ asset('uploads/articles/' ~ picture.photo) }}"
                             alt="{{ picture.photo }}">

                    {% endfor %}

                    {% if article.pictures |length > 1 %}
                        <div class="container__voir-commentaire">
                            <a class="lire-le-suite" href="{{ path('default_show', {'id': article.id}) }}">Voir toutes les
                                photos</a>
                        </div>
                    {% endif %}

                    <div class="container__texte">
                        <div class="container__nom">
                            <span>{{ article.utilisateur.prenom }}</span>
                            <span>{{ article.utilisateur.nom }}</span>
                        </div>
                        <div class="container__commune">
                            <span>{{ article.utilisateur.commune }} - </span>
                            <span>{{ article.utilisateur.departement }}</span>
                        </div>
                        <div class="container__commune">
                            <h4>{{ article.libelle }}</h4>
                            {% if article.texte()|length > 450 %}

                                <p class="container__p">
                                    {{ article.texte | striptags | slice(0, 450) }}
                                    ... <a class="lire-le-suite" href="{{ path('default_show', {'id': article.id}) }}">(Lire
                                        la suite)</a>
                                </p>

                            {% else %}
                                <p class="container__p">
                                    {{ article.texte }}
                                </p>
                            {% endif %}
                        </div>
                        {% if article.lienYoutube %}
                            {{ article.lienYoutube }}
                        {% endif %}
                    </div>
                </div>

                <div class="container__button-article-voir">
                    <a class="voir-produit" href="{{ path('default_show', {'id': article.id}) }}">Voir +</a>
                </div>

                {% for commentaire in article.commentaires | slice (0,3) %}

                    <div class="container__commentaire">

                        {% if commentaire.utilisateur.photo %}
                            <img class="photo_profil" src="{{ asset('uploads/' ~ commentaire.utilisateur.photo) }}"
                                 alt="{{ commentaire.utilisateur.photo }}">
                        {% else %}

                            <img class="avatar" src="{{ asset('images/avatar_default.svg') }}" alt="avatar">
                        {% endif %}


                        <div class="container__commentaire-texte">
                            <span class="container__commentaire-utilisateur">{{ commentaire.utilisateur }} :</span>
                            <span>{{ commentaire.texte }}</span>
                        </div>
                        <div class="container__date-commentaire">
                            <small>{{ commentaire.dateCreation ? commentaire.dateCreation|date('d-m-Y') : '' }}</small>
                        </div>
                    </div>

                {% endfor %}
                {% if article.commentaires |length > 3 %}
                    <div class="container__voir-commentaire">
                        <a class="lire-le-suite" href="{{ path('default_show', {'id': article.id}) }}">Voir tous les
                            commentaires</a>
                    </div>
                {% endif %}
                <div class="separation-article"></div>


            </div>
            {% endfor %}
        </div>



    <div class="main-evenement">
        {% for evenement in evenements %}


        <div class="container__evenement">
            <div class="container__evenement-titre">
                <h3>{{ evenement.libelle }}</h3>

            </div>
            <div class="container__evenement-contenu">
                <a href="{{ path('evenement_show', {'id': evenement.id}) }}"><img class="card-img-top" src="{{ asset('uploads/evenements/' ~ evenement.photo) }}"
                     alt="{{ evenement.photo }}"></a>
                <div class="container__evenement-texte">
                    <div class="container__evenement-nom">
                        <h5>{{ evenement.utilisateur.nomAssociation }}</h5>
                    </div>
                    <div class="container__evenement-commune">
                        <h6>{{ evenement.utilisateur.commune }} - {{ evenement.utilisateur.departement }}</h6>

                    </div>
                    <div class="container__evenement-commune">

                        {% if evenement.texte()|length > 450 %}

                            <p class="container__evenement-p">
                                {{ evenement.texte | striptags | slice(0, 450) }}
                                ... <a class="lire-le-suite"
                                       href="{{ path('evenement_show', {'id': evenement.id}) }}">(Lire
                                    la suite)</a>
                            </p>

                        {% else %}
                            <p class="container__evenement-p">
                                {{ evenement.texte }}
                            </p>
                        {% endif %}
                    </div>

                </div>
            </div>
            <div class="container__button-evenement-voir">
                <a class="voir-evenement" href="{{ path('evenement_show', {'id': evenement.id}) }}">Voir +</a>
            </div>

        </div>
            {% endfor %}

    </div>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog"
         aria-labelledby="exampleModalCenterTitle"
         aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Déconnexion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    Vous êtes sur le point de vous déconnecter
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Annuler</button>
                    <a class="a_deconnexion" href="/logout">Déconnexion</a>
                </div>
            </div>
        </div>
    </div>
    <div class="pagination d-flex justify-content-center">
        {{ knp_pagination_render(articles) }}
    </div>

{% endblock %}

templates/default/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <div class="container__show">


        <div class="container__article-show">
            <div class="container__article-titre-show">
                <h3>{{ article.album }}</h3>
                <p class="date-article">{{ article.dateCreation ? article.dateCreation|date('d-m-Y') : '' }}</p>
            </div>
            <div class="container__contenu-show">

                <div class="container__photo">

                    <div id="modal">
                        <div id="imgSizer">
                            <div id="imgHolder">
                                <img alt="Modal Image" id="modalImg">
                            </div>
                        </div>
                        <span id="close"><i class="fas fa-times"></i></span>
                        <button id="larr"><i class="fas fa-angle-left"></i></button>
                        <button id="rarr"><i class="fas fa-angle-right"></i></button>
                    </div>

                    <div id="gallery">
                        {% for picture in article.pictures | slice (0,1)%}


                            <img class="photo-article-show" src="{{ asset('uploads/articles/' ~ picture.photo) }}"
                                 alt="{{ picture.photo }}">

                        {% endfor %}
                        {% for picture in article.pictures | slice (1,10) %}
                            <img class="galerie-photo" style="width: 15%;" src="{{ asset('uploads/articles/' ~ picture.photo) }}"
                                 alt="{{ picture.photo }}">
                        {% endfor %}

                    </div>

                </div>
                <div class="container__texte-show">
                    <div class="container__nom">
                        <span>{{ article.utilisateur.prenom }}</span>
                        <span>{{ article.utilisateur.nom }}</span>
                    </div>
                    <div class="container__commune">
                        <span>{{ article.utilisateur.commune }} - </span>
                        <span>{{ article.utilisateur.departement }}</span>
                    </div>
                    <h4>{{ article.libelle }}</h4>
                    <p class="container__p-show">{{ article.texte }}</p>

                    {% if article.lienYoutube %}
                        {{ article.lienYoutube }}
                    {% endif %}
                </div>
            </div>

            {% if article.noKill %}
                <div class="no-kill">
                    <img id="nokill" class="nokill" src="{{ asset('images/no-kill.svg') }}" alt="logo to water">
                </div>
            {% endif %}

            <div class="container__button-article-retour">
                <a href="{{ path('homepage') }}" class="button-back">Retour</a>
            </div>

        </div>
        <div class="separation-article-show"></div>


        {% for commentaire in article.commentaires %}

            <div class="container__commentaire">

                {% if commentaire.utilisateur.photo %}
                    <img class="photo_profil" src="{{ asset('uploads/' ~ commentaire.utilisateur.photo) }}"
                         alt="{{ commentaire.utilisateur.photo }}">
                {% else %}

                    <img class="avatar" src="{{ asset('images/avatar_default.svg') }}" alt="avatar">
                {% endif %}


                <div class="container__commentaire-texte">
                    <span class="container__commentaire-utilisateur">{{ commentaire.utilisateur }} :</span>
                    <span>{{ commentaire.texte }}</span>
                </div>
                <div class="container__date-commentaire">
                    <small>{{ commentaire.dateCreation ? commentaire.dateCreation|date('d-m-Y') : '' }}</small>
                </div>
            </div>

        {% endfor %}
        <div class="container__commentaire-article">
            {% if app.user %}
                {{ render(controller('App\\Controller\\CommentaireController:new', {'id' : article.id })) }}
            {% endif %}
        </div>
        <div class="separation-article-show"></div>

    </div>



{% endblock %}