src/Entity/Produit.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\ProduitRepository")
 * @Vich\Uploadable
 * @ORM\HasLifecycleCallbacks
 */

class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @var \DateTime
     * @ORM\Column(name="date_creation", type="datetime", nullable=false)
     */
    private $date_creation;

    /**
     * @var \DateTime
     * @ORM\Column(name="date_maj", type="datetime", nullable=true)
     */
    private $date_maj;


    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="date_vente", type="datetime", nullable=true)
     */
    private $date_vente;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="produit_images", fileNameProperty="photo")
     * @var File
     * @Assert\Image(mimeTypes={ "image/jpeg", "image/jpg", "image/png"  }, mimeTypesMessage = "Extension valide : .jpeg .png .jpg", groups = {"create"})
     */
    private $photoFile;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="boolean")
     */
    private $mise_en_avant;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ProduitCategorie", inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\Column(type="text")
     */
    private $description;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getDateMaj(): \DateTime
    {
        return $this->date_maj;
    }

    public function setDateMaj(\DateTime $date_maj): Produit
    {
        $this->date_maj = $date_maj;
        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateVente(): ?\DateTimeInterface
    {
        return $this->date_vente;
    }

    public function setDateVente(?\DateTimeInterface $date_vente): self
    {
        $this->date_vente = $date_vente;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getPrix()
    {
        return $this->prix;
    }

    public function setPrix($prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getMiseEnAvant(): ?bool
    {
        return $this->mise_en_avant;
    }

    public function setMiseEnAvant(bool $mise_en_avant): self
    {
        $this->mise_en_avant = $mise_en_avant;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->Utilisateur;
    }


    public function setUtilisateur(?Utilisateur $Utilisateur): self
    {
        $this->Utilisateur = $Utilisateur;

        return $this;
    }


    public function getCategorie(): ?ProduitCategorie
    {
        return $this->categorie;
    }

    public function setCategorie(?ProduitCategorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function setPhotoFile(File $photo = null)
    {
        $this->photoFile = $photo;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($photo) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->date_maj = new \DateTime('now');
        }
    }

    public function getPhotoFile()
    {
        return $this->photoFile;
    }

    public function __toString()
    {
        return (string) $this->getCategorie();

    }

    /**
     * @ORM\PrePersist
     */
    public function prePersist()
    {
        $this->date_creation = new \DateTime();
    }

    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->date_maj = new \DateTime();
    }


}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UtilisateurRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class Utilisateur implements UserInterface, \Serializable
{


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $commune;


    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_web;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_association;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_president;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom_president;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="utilisateur")
     */
    private $evenements;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Produit", mappedBy="Utilisateur")
     */
    private $produits;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Album", mappedBy="utilisateur")
     */
    private $albums;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Aime", mappedBy="utilisateur")
     */
    private $aimes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Suivre", mappedBy="utilisateur_from")
     */
    private $suivis;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Suivre", mappedBy="utilisateur_to")
     */
    private $suiveurs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="utilisateur")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(name="photo", type="string", length=255, nullable=true)
     * @var string
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="utilisateur_images", fileNameProperty="photo")
     * @var File
     * @Assert\Image(mimeTypes={ "image/jpeg", "image/jpg", "image/png"  }, mimeTypesMessage = "Extension valide : .jpeg .png .jpg", groups = {"create"})
     */
    private $photoFile;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="utilisateur", orphanRemoval=true)
     */
    private $articles;





    public function __construct()
    {
        $this->evenements = new ArrayCollection();
        $this->produits = new ArrayCollection();
        $this->albums = new ArrayCollection();
        $this->aimes = new ArrayCollection();
        $this->suivis = new ArrayCollection();
        $this->suiveurs = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(string $commune): self
    {
        $this->commune = $commune;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(string $site_web): self
    {
        $this->site_web = $site_web;

        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(?string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(?string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getNomAssociation(): ?string
    {
        return $this->nom_association;
    }

    public function setNomAssociation(?string $nom_association): self
    {
        $this->nom_association = $nom_association;

        return $this;
    }

    public function getNomPresident(): ?string
    {
        return $this->nom_president;
    }

    public function setNomPresident(?string $nom_president): self
    {
        $this->nom_president = $nom_president;

        return $this;
    }

    public function getPrenomPresident(): ?string
    {
        return $this->prenom_president;
    }

    public function setPrenomPresident(?string $prenom_president): self
    {
        $this->prenom_president = $prenom_president;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setUtilisateur($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->contains($evenement)) {
            $this->evenements->removeElement($evenement);
            // set the owning side to null (unless already changed)
            if ($evenement->getUtilisateur() === $this) {
                $evenement->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setUtilisateur($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->contains($produit)) {
            $this->produits->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getUtilisateur() === $this) {
                $produit->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Album[]
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->albums->contains($album)) {
            $this->albums[] = $album;
            $album->setUtilisateur($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->albums->contains($album)) {
            $this->albums->removeElement($album);
            // set the owning side to null (unless already changed)
            if ($album->getUtilisateur() === $this) {
                $album->setUtilisateur(null);
            }
        }

        return $this;
    }

   

    

    /**
     * @return Collection|Aime[]
     */
    public function getAimes(): Collection
    {
        return $this->aimes;
    }

    public function addAime(Aime $aime): self
    {
        if (!$this->aimes->contains($aime)) {

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use DateTime;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichImageType;



class ProduitType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder

            ->add('libelle')
            ->add('description')
            ->add('photoFile', VichImageType::class, [
                'label' => 'Photo',
                'required' => false,])
            ->add('prix')
            ->add('categorie')
            ->add('miseEnAvant',CheckboxType::class, [
                "required" => false])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

templates/produit/_delete_form.html.twig
<form method="post" action="{{ path('produit_delete', {'id': produit.id}) }}" onsubmit="return confirm('Vous êtes sur le point de supprimer cet article');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/produit/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Valider') }}</button>
{{ form_end(form) }}

templates/produit/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Produit{% endblock %}

{% block body %}

    <h1>Edit Produit</h1>

    {{ include('produit/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('produit_index') }}">back to list</a>

    {{ include('produit/_delete_form.html.twig') }}
{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit index{% endblock %}

{% block body %}
    {% if app.user %}
        <div class="container">
            <div class="titre_page_produit">
                <h1 class="le_coin_titre">Gérez vos petites annonces</h1>
                <h4 class="le_coin_slogan">Vendez du matériel ou des prestations liées à la pratique de la pêche</h4>
                <p class="le_coin_slogan2">Professionnels ou amateurs</p>
            </div>
            <a class="creation_produit" href="{{ path('produit_new') }}">Déposer une annonce</a>


            {% for produit in app.user.produits %}

                <div class="container__produit">
                    <div class="container__produit-image">
                        <img class="image__produit" src="{{ asset('uploads/produits/' ~ produit.photo) }}"
                             alt="{{ produit.photo }}">
                    </div>
                    <div class="container__produit-body">
                        <h5 class="container__produit-title">{{ produit.libelle }}</h5>
                        {% if produit.description()|length > 300 %}

                            <p class="container__produit-text">
                                {{ produit.description | striptags | slice(0, 300) }}
                                ... <a class="lire-le-suite" href="{{ path('produit_show', {'id': produit.id}) }}">(Lire
                                    la suite)</a>
                            </p>

                        {% else %}
                            <p class="container__produit-text">
                                {{ produit.description }}
                            </p>
                        {% endif %}
                        <div class="container__produit-liens">
                            <a class="voir-produit" href="{{ path('produit_edit', {'id': produit.id}) }}">modifier</a>
                            <a class="voir-produit" href="{{ path('produit_show', {'id': produit.id}) }}">Voir +</a>

                        </div>
                    </div>
                </div>
            {% else %}

                <h2>Vous n'avez pas de produit</h2>

            {% endfor %}


        </div>
    {% else %}
        <div class="container">


            <div class="container_creer_compte">
                <h2>Vous devez être connecté pour consulter vos trucs</h2>
                <div class="container_creer_a">
                    <a class="creer_compte2" href="{{ path('app_register') }}">Créer un compte</a>
                    <a class="creer_compte2" href="/login">Me connecter</a>
                </div>
            </div>


        </div>
    {% endif %}
{% endblock %}

templates/produit/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Produit{% endblock %}

{% block body %}

    <div class="container">
        {% if app.user %}
            {{ include('produit/_form.html.twig') }}
        {% else %}


            <div class="container_creer_compte">
                <h2>Vous devez être connecté pour déposer une annonce</h2>
                <div class="container_creer_a">
                    <a class="creer_compte2" href="{{ path('app_register') }}">Créer un compte</a>
                    <a class="creer_compte2" href="/login">Me connecter</a>
                </div>
            </div>

        {% endif %}
    </div>
{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page Produit{% endblock %}

{% block body %}
    <div class="container">

    {% if app.user %}

        <div class="separation-produitshow"></div>
        <div class="container__produitshow">
            <div class="container__produitshow-title">
                <h2 class="card-title produitshow">{{ produit.libelle }}</h2>
                <div class="container__retour-button">

                </div>
            </div>
            <img class="container__produit-imgshow" src="{{ asset('uploads/produits/' ~ produit.photo) }}"
                 class="img-show"
                 alt="alt="{{ produit.photo }}">
            <div class="container__produit-texteshow">

                <span class="prix-produit-show">{{ produit.prix }} €</span>
                <p class="card-text">{{ produit.description }}</p>
                <div class="container__card-text">
                    <span>{{ produit.categorie }}</span>
                    <span>{{ produit.utilisateur.codePostal }} {{ produit.utilisateur.commune }}</span>
                    <span>{{ produit.dateCreation ? produit.dateCreation|date('d-m-Y') : '' }}</span>
                </div>
            </div>


            <div class="container__button-produit-show">

                <a href="{{ path('produit_index') }}" class="button-back">Retour</a>
            </div>
            </form>

        </div>




        </div>
    {% else %}
        <h5 class="card-title">{{ produit.libelle }}</h5>
        <img src="{{ asset('uploads/produits/' ~ produit.photo) }}" class="card-img" alt="alt="{{ produit.photo }}">
        <p class="card-text">{{ produit.description }}</p>
        <p class="card-text">
            <small class="text-muted">{{ produit.dateCreation ? produit.dateCreation|date('d-m-Y') : '' }}</small>
        </p>



    {% endif %}

    </div>



{% endblock %}