src/Entity/Evenement.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;


/**
 *
 * @ORM\Entity(repositoryClass="App\Repository\EvenementRepository")
 * @Vich\Uploadable
 */
class Evenement
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle;

    /**
     * @ORM\Column(type="text")
     */
    private $texte;

    /**
     * @ORM\Column(type="date")
     */
    private $date_evenement;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Utilisateur", inversedBy="evenements")
     * @ORM\JoinColumn(nullable=false)
     */
    private $utilisateur;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Evenement", inversedBy="evenements")
     */
    private $Evenement_categorie;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="Evenement_categorie")
     */
    private $evenements;

    /**
     * @ORM\Column(name="photo", type="string", length=255, nullable=true)
     * @var string
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="evenement_images", fileNameProperty="photo")
     * @var File
     * @Assert\Image(mimeTypes={ "image/jpeg", "image/jpg", "image/png"  }, mimeTypesMessage = "Extension valide : .jpeg .png .jpg", groups = {"create"})
     *
     */
    private $photoFile;

    /**
     * Evenement constructor.
     * @throws \Exception
     */
    public function __construct()
    {
        $this->evenements = new ArrayCollection();
        $this->setDateEvenement(new \DateTime());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    public function getTexte(): ?string
    {
        return $this->texte;
    }

    public function setTexte(string $texte): self
    {
        $this->texte = $texte;
        return $this;
    }

    public function getDateEvenement(): ?\DateTimeInterface
    {
        return $this->date_evenement;
    }

    public function setDateEvenement(\DateTimeInterface $date_evenement): self
    {
        $this->date_evenement = $date_evenement;

        return $this;
    }

    public function getUtilisateur(): ?Utilisateur
    {
        return $this->utilisateur;
    }

    public function setUtilisateur(?Utilisateur $utilisateur): self
    {
        $this->utilisateur = $utilisateur;

        return $this;
    }

    public function getEvenementCategorie(): ?self
    {
        return $this->Evenement_categorie;
    }

    public function setEvenementCategorie(?self $Evenement_categorie): self
    {
        $this->Evenement_categorie = $Evenement_categorie;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(self $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setEvenementCategorie($this);
        }

        return $this;
    }

    public function removeEvenement(self $evenement): self
    {
        if ($this->evenements->contains($evenement)) {
            $this->evenements->removeElement($evenement);
            // set the owning side to null (unless already changed)
            if ($evenement->getEvenementCategorie() === $this) {
                $evenement->setEvenementCategorie(null);
            }
        }

    
        return $this;
    }
    public function __toString()
    {
        return (string) $this->getUtilisateur();

    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }
    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;
        return $this;
    }

    public function setPhotoFile(File $photo = null)
    {
        $this->photoFile = $photo;

        // VERY IMPORTANT:
        // It is required that at least one field changes if you are using Doctrine,
        // otherwise the event listeners won't be called and the file is lost
        if ($photo) {
            // if 'updatedAt' is not defined in your entity, use another property
            $this->updatedAt = new \DateTime('now');
        }
    }

    public function getPhotoFile()
    {
        return $this->photoFile;
    }


}

src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\UserInterface;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UtilisateurRepository")
 * @UniqueEntity(fields={"email"}, message="There is already an account with this email")
 * @Vich\Uploadable
 */
class Utilisateur implements UserInterface, \Serializable
{


    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $commune;


    /**
     * @Assert\Regex("/^[0-9]{5}$/")
     * @ORM\Column(type="string", length=255)
     */
    private $code_postal;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $departement;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_web;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $siret;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_association;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $nom_president;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prenom_president;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Evenement", mappedBy="utilisateur")
     */
    private $evenements;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Produit", mappedBy="Utilisateur")
     */
    private $produits;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Album", mappedBy="utilisateur")
     */
    private $albums;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Aime", mappedBy="utilisateur")
     */
    private $aimes;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Suivre", mappedBy="utilisateur_from")
     */
    private $suivis;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Suivre", mappedBy="utilisateur_to")
     */
    private $suiveurs;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="utilisateur")
     */
    private $commentaires;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $password;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @ORM\Column(name="photo", type="string", length=255, nullable=true)
     * @var string
     */
    private $photo;

    /**
     * @Vich\UploadableField(mapping="utilisateur_images", fileNameProperty="photo")
     * @var File
     * @Assert\Image(mimeTypes={ "image/jpeg", "image/jpg", "image/png"  }, mimeTypesMessage = "Extension valide : .jpeg .png .jpg", groups = {"create"})
     */
    private $photoFile;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Article", mappedBy="utilisateur", orphanRemoval=true)
     */
    private $articles;





    public function __construct()
    {
        $this->evenements = new ArrayCollection();
        $this->produits = new ArrayCollection();
        $this->albums = new ArrayCollection();
        $this->aimes = new ArrayCollection();
        $this->suivis = new ArrayCollection();
        $this->suiveurs = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->articles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCommune(): ?string
    {
        return $this->commune;
    }

    public function setCommune(string $commune): self
    {
        $this->commune = $commune;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->code_postal;
    }

    public function setCodePostal(string $code_postal): self
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getDepartement(): ?string
    {
        return $this->departement;
    }

    public function setDepartement(string $departement): self
    {
        $this->departement = $departement;

        return $this;
    }

    public function getSiteWeb(): ?string
    {
        return $this->site_web;
    }

    public function setSiteWeb(string $site_web): self
    {
        $this->site_web = $site_web;

        return $this;
    }

    public function getNomEntreprise(): ?string
    {
        return $this->nom_entreprise;
    }

    public function setNomEntreprise(?string $nom_entreprise): self
    {
        $this->nom_entreprise = $nom_entreprise;

        return $this;
    }

    public function getSiret(): ?string
    {
        return $this->siret;
    }

    public function setSiret(?string $siret): self
    {
        $this->siret = $siret;

        return $this;
    }

    public function getNomAssociation(): ?string
    {
        return $this->nom_association;
    }

    public function setNomAssociation(?string $nom_association): self
    {
        $this->nom_association = $nom_association;

        return $this;
    }

    public function getNomPresident(): ?string
    {
        return $this->nom_president;
    }

    public function setNomPresident(?string $nom_president): self
    {
        $this->nom_president = $nom_president;

        return $this;
    }

    public function getPrenomPresident(): ?string
    {
        return $this->prenom_president;
    }

    public function setPrenomPresident(?string $prenom_president): self
    {
        $this->prenom_president = $prenom_president;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setUtilisateur($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->contains($evenement)) {
            $this->evenements->removeElement($evenement);
            // set the owning side to null (unless already changed)
            if ($evenement->getUtilisateur() === $this) {
                $evenement->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Produit[]
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): self
    {
        if (!$this->produits->contains($produit)) {
            $this->produits[] = $produit;
            $produit->setUtilisateur($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): self
    {
        if ($this->produits->contains($produit)) {
            $this->produits->removeElement($produit);
            // set the owning side to null (unless already changed)
            if ($produit->getUtilisateur() === $this) {
                $produit->setUtilisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Album[]
     */
    public function getAlbums(): Collection
    {
        return $this->albums;
    }

    public function addAlbum(Album $album): self
    {
        if (!$this->albums->contains($album)) {
            $this->albums[] = $album;
            $album->setUtilisateur($this);
        }

        return $this;
    }

    public function removeAlbum(Album $album): self
    {
        if ($this->albums->contains($album)) {
            $this->albums->removeElement($album);
            // set the owning side to null (unless already changed)
            if ($album->getUtilisateur() === $this) {
                $album->setUtilisateur(null);
            }
        }

        return $this;
    }

   

    

    /**
     * @return Collection|Aime[]
     */
    public function getAimes(): Collection
    {
        return $this->aimes;
    }

    public function addAime(Aime $aime): self
    {
        if (!$this->aimes->contains($aime)) {

src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/evenement")
 */
class EvenementController extends AbstractController
{
    /**
     * @Route("/", name="evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findBy(["utilisateur" => $this->getUser()], ["date_evenement" => "DESC"]),
        ]);
    }

    /**
     * @Route("/new", name="evenement_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $evenement = new Evenement();
        $evenement->setUtilisateur($this->getUser());
        $evenement->setDateEvenement(new \DateTime('now'));
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index');
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="evenement_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Evenement $evenement): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('evenement_index', [
                'id' => $evenement->getId(),
            ]);
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Evenement $evenement): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evenement_index');
    }
}

templates/evenement/_delete_form.html.twig
<form method="post" action="{{ path('evenement_delete', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
    <button class="btn">Delete</button>
</form>

templates/evenement/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/evenement/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Evenement{% endblock %}

{% block body %}
    <h1>Edit Evenement</h1>

    {{ include('evenement/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('evenement_index') }}">back to list</a>

    {{ include('evenement/_delete_form.html.twig') }}
{% endblock %}

templates/evenement/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Evenements{% endblock %}

{% block body %}
    <div class="container">
        {% if app.user %}
            <div class="container-titre-evenement">
                <h1 class="mes-evenements"><i class="fas fa-image"></i> Mes événements...</h1>
            </div>
            <div class="separation-evenement-titre"></div>
            <a class="creation_produit" href="{{ path('evenement_new') }}">Poster un evenement</a>
            <div class="separation-evenement"></div>

            {% for evenement in evenements %}
                <div class="container__evenement">
                    <div class="container__evenement-titre">
                        <h3>{{ evenement.libelle }}</h3>
                        <p class="date-article">{{ evenement.dateEvenement ? evenement.dateEvenement|date('d-m-Y') : '' }}</p>
                    </div>
                    <div class="container__contenu-evenement">
                        <img class="card-img-top" src="{{ asset('uploads/evenements/' ~ evenement.photo) }}"
                             alt="{{ evenement.photo }}">
                        <div class="container__texte-evenement">
                            <div class="container__nom">
                                <span>{{ app.user.prenom }}</span>
                                <span>{{ app.user.nom }}</span>
                            </div>
                            <div class="container__commune-evenement">
                                <span>{{ app.user.commune }} - </span>
                                <span>{{ app.user.departement }}</span>
                            </div>
                            <div class="container__commune-evenement">

                                {% if evenement.texte()|length > 450 %}

                                    <p class="container__p">
                                        {{ evenement.texte | striptags | slice(0, 450) }}
                                        ... <a class="lire-le-suite"
                                               href="{{ path('evenement_show', {'id': evenement.id}) }}">(Lire la
                                            suite)</a>
                                    </p>

                                {% else %}
                                    <p class="container__p-evenement">
                                        {{ evenement.texte }}
                                    </p>
                                {% endif %}
                            </div>

                        </div>
                    </div>
                    <a href="{{ path('evenement_show', {'id': evenement.id}) }}">Voir +</a>
                    <a href="{{ path('evenement_edit', {'id': evenement.id}) }}">Modifier</a>
                </div>

                <div class="separation-evenement"></div>
            {% endfor %}





        {% else %}

            <div class="container_creer_compte">
                <h2>Vous devez être connecté pour consulter vos évenements</h2>
                <div class="container_creer_a">
                    <a class="creer_compte2" href="{{ path('app_register') }}">Créer un compte</a>
                    <a class="creer_compte2" href="/login">Me connecter</a>
                </div>
            </div>
        {% endif %}
    </div>
    </div>
{% endblock %}

templates/evenement/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Evenement{% endblock %}

{% block body %}
    <h1>Create new Evenement</h1>

    {{ include('evenement/_form.html.twig') }}

    <a href="{{ path('evenement_index') }}">back to list</a>
{% endblock %}

templates/evenement/show.html.twig
{% extends 'base.html.twig' %}



    {% block title %}Article{% endblock %}

    {% block body %}
        <div class="container__show">


            <div class="container__evenement-show">
                <div class="container__evenement-titre-show">
                    <h3>{{ evenement.libelle }}</h3>
                    <p class="date-article">{{ evenement.dateEvenement ? evenement.dateEvenement|date('d-m-Y') : '' }}</p>
                    <span>{{ evenement.utilisateur.nomAssociation }}</span>
                    <div class="container__commune-evenement-show">
                        <span>{{ evenement.utilisateur.commune }} - </span>
                        <span>{{ evenement.utilisateur.departement }}</span>
                    </div>
                </div>
                <div class="container__contenu-evenement-show">
                    <img class="card-img-top" src="{{ asset('uploads/evenements/' ~ evenement.photo) }}"
                         alt="{{ evenement.photo }}">
                    <div class="container__texte-evenement-show">


                        <h4>{{ evenement.libelle }}</h4>
                        <p class="container__p-evenement-show">{{ evenement.texte }}</p>


                    </div>
                </div>

            </div>
            <div class="container__evenement-show-retour">
                <a class="voir-produit" href="{{ path('homepage') }}">Retour</a>
            </div>

            <div class="separation-article-show"></div>


        </div>

    {% endblock %}